# Generated by Django 4.0.1 on 2022-02-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterDATABASE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField(null=True)),
                ('ip_address', models.TextField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('severity', models.TextField(null=True)),
                ('cvss', models.TextField(null=True)),
                ('publication_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5),
        ),
    ]
